<?xml version="1.0"?>
<!--
	ArchE
	Copyright (c) 2012 Carnegie Mellon University.
	All Rights Reserved.

	Redistribution and use in source and binary forms, with or without
	modification, are permitted provided that the following conditions are met:

	1. Redistributions of source code must retain the above copyright notice,
	this list of conditions and the following acknowledgments and disclaimers.

	2. Redistributions in binary form must reproduce the above copyright notice,
	this list of conditions and the following disclaimer in the documentation
	and/or other materials provided with the distribution.

	3. All advertising materials for third-party software mentioning features or
	use of this software must display the following disclaimer:

	“Neither Carnegie Mellon University nor its Software Engineering Institute
	have reviewed or endorsed this software”

	4. The names “Carnegie Mellon University,” and/or “Software Engineering
	Institute" shall not be used to endorse or promote products derived from
	this software without prior written permission. For written permission,
	please contact permission@sei.cmu.edu.

	5. Redistributions of any form whatsoever must retain the following
	acknowledgment:

	Copyright 2012 Carnegie Mellon University.

	This material is based upon work funded and supported by the United States
	Department of Defense under Contract No. FA8721-05-C-0003 with Carnegie
	Mellon University for the operation of the Software Engineering Institute, a
	federally funded research and development center.

	NO WARRANTY

	THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL
	IS FURNISHED ON AN “AS-IS” BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO
	WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER
	INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR
	MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL.
	CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH
	RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
-->
<!DOCTYPE Properties [
  <!ELEMENT Properties    (Option*)>
  <!ELEMENT FactSet    	  (OptionName,OptionCode+)>
  <!ELEMENT OptionName    (#PCDATA)>
  <!ELEMENT OptionCode    (#PCDATA)>
]>
<Properties>
<!-- The following parameters can be used
     %M will be substituted by the module name in which this option is defined
     %1, %2, ...%n are the parameters given in the definition of the option
 -->
  <Option>
  	<OptionName>Debug</OptionName>
  	<OptionCode> 
		(defrule __Debug%MEnter
		    (declare (salience 1000))
		    (MAIN::Debug %M ?trace ?break)
		=>
		    (printout t "***Entered %M" crlf)
		    (if (neq ?trace none) then
		        (watch ?trace))
		    (if ?break then
		        (printout t "   Stopped at beginning of module %M" crlf)
		        (halt))
		)
  	</OptionCode>
  	<OptionCode>
		(defrule __Debug%MExit
		    (declare (salience -1000))
		    ?d &lt;- (MAIN::Debug %M ?trace ?break)
		=>
		    (printout t "***Exited  %M" crlf)
		    (if (neq ?trace none) then
		        (unwatch ?trace))
		    (retract ?d)
		    (assert (MAIN::Debug %M ?trace ?break))
		    (return)
		)
  	</OptionCode>
  </Option>
  <Option>
  	<OptionName>Sequence</OptionName>
  	<OptionCode>       <!-- The initial rule -->
		(defrule __%MScheduler%1
		    (declare (salience -110))
		    (not (T_ControlModelExecution ?))
		=>
		    (assert (T_ControlModelExecution %1))
		 )
  	</OptionCode>
  	<OptionCode>       <!-- This rule will be repeated for each state-->
		(defrule __%MScheduler%2
		    (declare (salience -110))
		    ?t &lt;- (T_ControlModelExecution %1)
		=>
		    (retract ?t)
		    (assert (T_ControlModelExecution %2))
		)
  	</OptionCode>
  	<OptionCode>       <!-- The final rule -->
		(defrule __%MSchedulerCleanupNoDebug
		    (declare (salience -131))
		    ?t &lt;- (T_ControlModelExecution %1)
		=>
		    (retract ?t)
		    (return)
		)
		(defrule __%MSchedulerCleanupDebug
		    (declare (salience -130))
		    ?t &lt;- (T_ControlModelExecution %1)
		    ?d &lt;- (MAIN::Debug %M ?trace ?break)
		=>
		    (retract ?t)
		    (printout t "***Exited  %M" crlf)
		    (if (neq ?trace none) then
		        (unwatch ?trace))
		    (retract ?d)
		    (assert (MAIN::Debug %M ?trace ?break))
		    (return)
		)
  	</OptionCode>
  </Option>
  <Option>
  	<OptionName>Events</OptionName>
  	<OptionCode>       <!-- Make the start of the enter event -->
		(defrule __%MOnEnterStart
		    (declare (salience 101))
		    (Planner::T_MakeAnotherRound)
		=>
		    (assert (OnEnter))
		 )
  	</OptionCode>
  	<OptionCode>       <!-- End of the enter event -->
		(defrule __%MOnEnterStop
		    (declare (salience -101))
		    ?t &lt;- (OnEnter)
		=>
		    (retract ?t)
		)
  	</OptionCode>
  	<OptionCode>       <!-- Make the start of the exit event -->
		(defrule __%MOnExitStart
		    (declare (salience -120))
		    (not (OnEnter))
		=>
		    (assert (OnExit))
		 )
  	</OptionCode>
  	<OptionCode>       <!-- End of the exit event -->
		(defrule __%MOnExitStop
		    (declare (salience -120))
		    ?t &lt;- (OnExit)
		=>
		    (retract ?t)
		    (return)
		)
  	</OptionCode>
  </Option>
</Properties>